### ISSUE TITLE
Remove NAT Address?

### ISSUE THREAD

**Issue by codejp3** [hestiacp/hestiacp#1331]
Quick question. I'm trying to setup an intranet (local-only) site and using Hestia as the backbone. How can I set it up so that Hestia does NOT use a NAT IP, and only responds to requests on the interface static IP? 

Coming from Vesta a while ago, it had a network/IP configuration section in the admin panel. I vaguely recall older versions of Hestia having it as well. 

I'm on Ubuntu 20.04
Using netplan (see YAML config below)
On the latest stable Hestia

netplan YAML (X's are sensitive IP/network info):
```
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      addresses:
        - XXX.XXX.X.X/XX
      gateway4: XXX.XXX.X.X
      nameservers:
          search: [XXX, XXX.XXX]
          addresses: [XXX.XXX.XXX.XXX, XXX.XXX.XXX.XXX]
```

I've tried running these commands:

`v-change-sys-ip-nat XXX.XXX.X.X`
(without a NAT IP at all)
results in:
`Usage: v-change-sys-ip-nat IP NAT_IP [RESTART]`

and
`v-change-sys-ip-nat XXX.XXX.X.X XXX.XXX.X.X`
(repeating the static IP as the NAT IP)
results in:
`sed: can't read /usr/local/hestia/data/users/admin/dns/*.conf: No such file or directory`

Repeating the question, how can I setup Hestia so that it does NOT use a NAT IP, and only responds to requests on the interface static IP?  Thanks in advance!
