### ISSUE TITLE
Cleanup theme system css

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#3456]
### Describe the feature or change in detail

As a followup to https://github.com/hestiacp/hestiacp/issues/2493

The documentation has improved a lot, I have to say! https://hestiacp.com/docs/server-administration/customisation.html#customising-a-default-theme

However:
- jaap mentioned that the theme variables are not yet used consistently
- there seems to be an abundance of code duplication between the themes, DRY should be employed to make customizations clearer, I guess by making a base theme or something

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
Compared with the old 1.6 theme and 1.7 theme there has been already a massive clean up. 

1.6 https://github.com/hestiacp/hestiacp/blob/releases/v1.6/web/css/src/themes/default.css
vs 
1.7 https://github.com/hestiacp/hestiacp/blob/release/web/css/src/themes/default.css

It looks like the docs needs to be updated

**Comment by AlecRust** [comment]
> jaap mentioned that the theme variables are not yet used consistently

This is a slow, ongoing process. Feel free to contribute PRs.

> there seems to be an abundance of code duplication between the themes, DRY should be employed to make customizations clearer, I guess by making a base theme or something

This should no longer be the case. Please provide examples if you think it is. `default.css` is already the "base theme" that all other themes override.

**Comment by jaapmarcus** [comment]
I am going to close the issue. It is a work in progress anyway

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/3457

Will solve the second issue

**Comment by xeruf** [comment]
yes I very much appreciate the progress here, yet just looking at the first 50 lines of flat and vestia I feel almost half is duplication, making customization unwieldy because you first have to separate out what matters

**Comment by jaapmarcus** [comment]
It is caused by the fact both the default and dark theme have box shadows and for the non box shadow themes we need to overwrite it. 

We have made in the last few months major changes to it and we @AlecRust  is currently working on some rewrites on the javascript but it will take some time / effort.

**Comment by AlecRust** [comment]
As @jaapmarcus says it's not really my area of focus for now. But vast majority of CSS has been rewritten and should be perfectly "customisable".

@xeruf can you be more specific about the issues you're having? We have some basic CSS vars, but they aren't well integrated yet. As Jaap says, `default` is the base and all other themes are override layers on top of this.

Long term, you should be able to fully customise the theme with only CSS vars e.g.

```css
:root {
  --color-base-background: #444;
  --color-dialog-text: #fff;
  --border-radius-base: 10px;
  /* etc. all other main things */
}
```

In the shorter term, you can fully customise the theme with some CSS vars, and override CSS e.g.

```css
:root {
  --chart-label-color: #7c7c7c;
  --chart-grid-color: #e9e9e9;
  /* some other vars listed in default.css */
}

/* Overrode menu toggle styles */
.main-menu-toggle-label {
  color: red;
}

/* etc. any other styles you need */
```

Please let me know the issues you're having with this approach, it should be quite straightforward..
